application: rflectevents
version: 1a
runtime: python
api_version: 1

default_expiration: "0d"

handlers:
- url: /
  script: main.py

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: (.*)/rflectcalendar-images.png
  static_files: img/rflectcalendar-images.png
  upload: (.*)/rflectcalendar-images.png
  mime_type: "image/png"

- url: .*/css/(.*).css
  static_files: css/\1.css
  upload: .*/css/(.*).css
  mime_type: "text/css"

- url: .*/src/(.*).js
  static_files: src/\1.js
  upload: .*/src/(.*).js
  mime_type: "application/javascript"

- url: .*/templates/(.*).html
  static_files: templates/\1.html
  upload: .*/templates/(.*).html
  mime_type: "text/html"

- url: /manifest/(.*\.appcache)
  static_files: manifest/\1
  mime_type: text/cache-manifest
  upload: manifest/(.*\.appcache)

- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /.*
  script: djangoappengine/main/main.py
